### ISSUE TITLE
Task_1_checklist_completed

### ISSUE THREAD

**Issue by SaberOrien** [SaberOrien/ProgrammingTechnologies_24#3]
# Task 1 Check list

- [x] text is in C# and use .NET
![image](https://github.com/SaberOrien/ProgrammingTechnologies_24/assets/115357207/6ede9909-1e0d-4e0a-bd3f-982867007f00)
- [x] build succeeded
![image](https://github.com/SaberOrien/ProgrammingTechnologies_24/assets/115357207/3eacea2d-a1fc-418c-81a1-597b213431ec)
- [x] all UT are green
![image](https://github.com/SaberOrien/ProgrammingTechnologies_24/assets/115357207/b6efccef-2084-48dd-933b-912a2de44c06)
- [x] Object model representing process data
  - [x] structured data is used to create object model
![image](https://github.com/SaberOrien/ProgrammingTechnologies_24/assets/115357207/18f60549-09cf-4d9a-ad4a-2fc3887e6181)
  - [x] Users: a collection of all actors relevant to the implemented business process (e.g.: readers, customers, suppliers, etc)
![image](https://github.com/SaberOrien/ProgrammingTechnologies_24/assets/115357207/0f25e413-89ad-4369-8450-85903671ac1f)
  - [x] Catalog: a dictionary of the goods descriptions (e.g.: books, good )
![image](https://github.com/SaberOrien/ProgrammingTechnologies_24/assets/115357207/fcfeaca1-35df-4d56-8462-8f2bf2881b7c)
  - [x] Process state: description of the current process state (e.g: the current content of the shop, library, etc.)
![image](https://github.com/SaberOrien/ProgrammingTechnologies_24/assets/115357207/d013c166-e38a-4828-9c85-261527cab6c2)
  - [x] Events:  description of all events contributing to the process state change in time.
![image](https://github.com/SaberOrien/ProgrammingTechnologies_24/assets/115357207/0129d962-3550-4cc6-8475-53be5bcaab1e)
- [x] Dependency injection (additional framework is not required)
![image](https://github.com/SaberOrien/ProgrammingTechnologies_24/assets/115357207/0c219d97-c72c-41b3-8187-26bacc7dbc9e)
- [x] `Data` layer is clearly stated (no database of file access is required)
![image](https://github.com/SaberOrien/ProgrammingTechnologies_24/assets/115357207/af0c111a-c6c8-4a95-aded-a91a02fbedf5)
- [x] `Data` API is abstract
![image](https://github.com/SaberOrien/ProgrammingTechnologies_24/assets/115357207/94de86e7-6dc5-4971-bf12-24a5fb28c18c)
- [x] `Logic` layer is clearly stated
![image](https://github.com/SaberOrien/ProgrammingTechnologies_24/assets/115357207/742550bf-23d3-4cb5-a55b-3240cce9614a)
- [x] `Logic` API is clearly stated
![image](https://github.com/SaberOrien/ProgrammingTechnologies_24/assets/115357207/13506e38-b52f-408e-bd6c-d9c235a6703e)
- [x] `Logic` uses only the abstract `Data` layer API
![image](https://github.com/SaberOrien/ProgrammingTechnologies_24/assets/115357207/7f6743fd-9bcd-4dc3-a8e4-384764a8cf9f)
- [x] Unit Test - 2+ testing data generation methods
![image](https://github.com/SaberOrien/ProgrammingTechnologies_24/assets/115357207/5ea300e2-8919-4b14-8376-30c4d1818ff4)
- [x] layers are tested independently
![image](https://github.com/SaberOrien/ProgrammingTechnologies_24/assets/115357207/3522ede4-c925-4213-bc4e-6903c41a55b0)
- [x] only code in the solution is tested
![image](https://github.com/SaberOrien/ProgrammingTechnologies_24/assets/115357207/bd3d97d5-5769-4dc2-ba89-90625ca82dd7)

**Comment by SaberOrien** [comment]
Completed the checklist with proof.
